name: training
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.9.0
  - pip>=22.2.0
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit
  - huggingface_hub
  - diffusers==0.6.0
  - pytorch-cuda=11.7
  - torchaudio
  - numpy
  - pip:
    - getpass_asterisk
    - dependency_injector==4.40.0
    - realesrgan==0.2.5.0
    - test-tube==0.7.5
    - pytorch-lightning
    - transformers
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
    - -e git+https://github.com/invoke-ai/clipseg.git@models-rename#egg=clipseg
    - -e .
