steps:
# - name: gcr.io/cloud-builders/docker
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook', './docker/notebook']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training', './docker/training']
  waitFor: ['-']
# kaniko testing
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook-kaniko
#   - --context=./docker/notebook
#   - --cache=true
#   - --cache-ttl=6h
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training-kaniko
#   - --context=./docker/training
#   - --cache=true
#   - --cache-ttl=6h
options:
  machineType: 'E2_HIGHCPU_8'
images:
# - 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook'
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training'

# steps:
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook
#   - --context=./docker/notebook
#   - --cache=true
#   - --cache-ttl=XXh
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training
#   - --context=./docker/training
#   - --cache=true
#   - --cache-ttl=XXh
# options:
#   machineType: 'E2_HIGHCPU_8'
