steps:
# - name: gcr.io/cloud-builders/docker
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook', './docker/notebook']

# https://cloud.google.com/build/docs/optimize-builds/speeding-up-builds#caching_directories_with_google_cloud_storage
# - name: gcr.io/cloud-builders/docker
#   id: base
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/base', './docker/base']
#   waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/training', './docker/training']
- name: gcr.io/cloud-builders/docker
  id: process
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/process', './docker/process']
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/server', './model-server']
  waitFor: ['process']
# kaniko testing
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook-kaniko
#   - --context=./docker/notebook
#   - --cache=true
#   - --cache-ttl=6h
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training-kaniko
#   - --context=./docker/training
#   - --cache=true
#   - --cache-ttl=6h
options:
  # since most of the build time is conda (python) setting up the environment
  # we can't take advantage of multiple cpus
  machineType: 'E2_HIGHCPU_8'
images:
# - 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook'
# - 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/base'
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/training'
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/process'
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/server'

# steps:
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook
#   - --context=./docker/notebook
#   - --cache=true
#   - --cache-ttl=XXh
# - name: 'gcr.io/kaniko-project/executor:latest'
#   waitFor: ['-']
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training
#   - --context=./docker/training
#   - --cache=true
#   - --cache-ttl=XXh
# options:
#   machineType: 'E2_HIGHCPU_8'
