# steps:
# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/stable
#   - --cache=true
#   - --cache-ttl=6h
#   - --context=docker

steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/stable', './docker']
images:
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/stable'
