steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook', './docker/notebook']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training', './docker/training']
  waitFor: ['-']
options:
  machineType: 'E2_HIGHCPU_8'
images:
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/notebook'
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/cuda/training'

