apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-server
  labels:
    app: stable-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-server
  template:
    metadata:
      labels:
        app: stable-server
    spec:
      containers:
      - name: stable-server
        image: us-central1-docker.pkg.dev/md-demos/stable-app/model-server:1
        ports:
        - containerPort: 5000
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100

