image:
  repository: us-central1-docker.pkg.dev/md-demos/stable-app/simple-server
  tag: "1"

command: []
args: []

envs: []
port: 5000

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits:
  nvidia.com/gpu: 1

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

commonLabels: {}

pod:
  annotations: {}

# gke-specific
nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-tesla-p100
