name: stable-app
channels:
  - pytorch
  - conda-forge
  - defaults
pkgs_dirs:
  - /root/.cache/conda
dependencies:
  - python=3.10
  - pytorch=1.13
  - torchvision=0.14

  - pip=22.3.1
  - numpy
  - torchaudio
  # dont need for tpus
  # - cudatoolkit=11.6
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.5.5.64
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.7.7
    - omegaconf==2.2.3
    - test-tube>=0.7.5
    - streamlit==1.12.0
    - send2trash==1.8.0
    - pillow==9.2.0
    - einops==0.3.0
    - pyreadline3
    - torch-fidelity==0.3.0
    - transformers==4.21.3
    - diffusers==0.6.0
    - torchmetrics==0.7.0
    - flask==2.1.3
    - flask_socketio==5.3.0
    - flask_cors==3.0.10
    - dependency_injector==4.40.0
    - eventlet
    - getpass_asterisk
    - kornia==0.6.0
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e git+https://github.com/invoke-ai/Real-ESRGAN.git#egg=realesrgan
    - -e git+https://github.com/invoke-ai/GFPGAN.git#egg=gfpgan
    - -e git+https://github.com/invoke-ai/clipseg.git@models-rename#egg=clipseg
    - -e .
