name: base
channels:
  - conda-forge
  - pytorch-nightly
  - nvidia
  - defaults
dependencies:
  - python>=3.9.0
  - pip>=22.2.0
  # nightly install
  - cudatoolkit
  - pytorch
  - torchvision
  - accelerate=0.12.0
  - diffusers==0.6.0
  - pytorch-cuda=11.7
  - numpy
  # hyper parameter tuning
  - ray





